server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-30874912.okta.com/oauth2/default
    client-id: 0oa5z084vdiAnDMzc5d7
    client-secret: ChZfYUWO82GYxVzHwuLYb-n5hrpA67jRhJAeQFBK
spring:
  thymeleaf:
    cache: false
